#+TITLE: Effect of Choice and Loyalty on Bertrand Equilibria in Posted Offer Markets
#+AUTHOR: Horatio Caine and Michal Staniaszek
#+LATEX_HEADER: \usepackage{fullpage}
#+OPTIONS: toc:nil

* What
- Effect of Choice and Loyalty on Bertrand Equilibria in Posted Offer Markets
- Simple posted offer market (General case)
  + Assume one product, two manufacturers
  + Assume homogeneous products
  + Normally, it is assumed that consumers choose cheapest
  + Theoretical effect is that posted price converges to Marginal Cost (due to manufacturers competing for profits)

- Our version
  + Probabilistic choosing between brands (with threshold indicating reluctance to pay too much)
  + Multiple products
  + Many manufacturers
  + Only one shop - no search cost for consumers (standard assumption in Economics)
- What are the effects?
  + Theoretical effect is prices converge to Marginal Cost
  + Does our model reproduce this effect?
* Definition
- 'Village', large population
- Multiple products
  + 'Essentials' (everybody buys them)
- Many consumers
  + Consumer is assumed to be a household
  + Household income based on a gaussian distribution over population
  + Different requirements of 'essentials', e.g. larger families require more food - generate via gaussian in the range [0,infinity]
  + No variation in the number of purchases made daily
  + Each customer attempts to stay loyal to one manufacturer
  + Customers change loyalty when they purchase more products from a manufacturer which is not their preferred one
- Multiple manufacturers
  + Same village, therefore same production cost (i.e. marginal cost)
  + Price can change daily
  + Each aims to increase profit. Manufacturers change price and see what happens. If profit increases, they keep going, if decreases, they do the opposite. Apply upper threshold so as not to 'rip-off' consumers, lower threshold is Marginal Cost
- Consumer choice function
  + If the preferred manufacturer's product is the cheapest, always buy it. Otherwise, the product is chosen proportionally to the difference in price between the preferred manufacturer's product and the cheapest product. Consumers become more likely to switch to a different manufacturer the greater the price difference
* Simulation
- Show price from each manufacturer (maybe graph)
- Show profit of each manufacturer (maybe graph)
- Large population/many products/many manufacturers competing

* Validation
- Expect to see race to the bottom with prices in simple scenario
- Removing competitors causes greedy price increases
- Adding competitors doesn't decrease prices
- See how consumer loyalty changes over time. We predict that in the end, consumers become loyal to the company that became cheapest first
- See how much switching is being done between manufacturers. We predict that there will be a lot of switching of loyalty at the start due to high price variation, but as equilibrium is approached this should become minimal
