#!/bin/bash
gnuplot plotprice.gnu &
PRICEPID=$!

gnuplot plotprofit.gnu &
PROFITPID=$!

gnuplot plotloyalty.gnu &
LOYALTYPID=$!

# echo "Type 'exit' to exit"

while read line; do
    if [ "$line" == "exit" ]; then
        echo "Killing..."
        kill $PRICEPID
        kill $PROFITPID
        kill $LOYALTYPID
        exit
    fi
done

#read -p "Type 'exit' to exit: "

