#!/bin/bash
gnuplot << EOF &
call "plotprice.gnu" $1
EOF
PRICEPID=$!

gnuplot << EOF &
call "plotprofit.gnu" $1
EOF
PROFITPID=$!

gnuplot << EOF &
call "plotloyalty.gnu" $1
EOF
LOYALTYPID=$!

echo "Type 'exit' to exit"

while read line; do
    if [ "$line" == "exit" ]; then
        echo "Killing..."
        kill $PRICEPID
        kill $PROFITPID
        kill $LOYALTYPID
        exit
    fi
done

#read -p "Type 'exit' to exit: "

