#!/bin/bash
LOGDIR=logs
PROFITFILE=$LOGDIR/profit.dat
PRICEFILE=$LOGDIR/price.dat
LOYALTYFILE=$LOGDIR/loyalty.dat

if [ ! -d $LOGDIR ]; then
    mkdir $LOGDIR
fi

make

# If make was successful, run the program run plot script in the background
if [ $? -eq 0 ]; then
    if [ -f $PROFITFILE ]; then
        rm $PROFITFILE
    fi
    if [ -f $PRICEFILE ]; then
        rm $PRICEFILE
    fi
    if [ -f $LOYALTYFILE ]; then
        rm $LOYALTYFILE
    fi

   ./bin/release/equilibria 16 16 $1 $PROFITFILE $PRICEFILE $LOYALTYFILE $2 &
   sleep 1
   
   # Wait until all files for plotting exist
   while [[ ! -f $PROFITFILE  || ! -f $PRICEFILE || ! -f $LOYALTYFILE ]]; do
       echo "Waiting for plot files..."
       sleep 1
   done
   
   ./plot
fi
